title: Karolina Bloch
logo: /assets/img/profile_photo_circle.jpg
description: A data analyst with a versatile background spanning both client-facing roles—ecommerce sales, client service—and back-office functions like financial reporting and analysis. Skilled in Excel, SQL, and Tableau, with a proven record of optimizing processes through data-driven insights. Equipped with natural curiosity and attention to detail, I’m eager to apply my experience to uncover trends, stay on guard of data accuracy, and develop insights in a data analyst role. I excel in remote work arrangements, where I can use my strong self-management and proactive communication skills.
show_downloads: false
theme: jekyll-theme-minimal
